### ISSUE TITLE
Not working with banners

### ISSUE THREAD

**Issue by TomJansen** [nikosdion/joomlasvg#1]
Hello! I really like this plugin and it's a great addition! However, I want to use an .svg as banner image (sponsors), but when I upload and publish the banner, it does not show the svg, not even the <img> tag.

Is this fixable? Thanks

**Comment by nikosdion** [comment]
Good catch. Apparently Joomla is patently bad at consistency and code reuse. `com_banners` had its own helper to determine what is an image instead of using the Media component options. I changed to code to fix that. I will tag and release v.1.0.1 shortly.

**Comment by nikosdion** [comment]
Please find the new release here: https://github.com/nikosdion/joomlasvg/releases/tag/1.0.1
