### ISSUE TITLE
Only .svg uploading works now

### ISSUE THREAD

**Issue by TomJansen** [nikosdion/joomlasvg#2]
Hi,
First off I don't want to be needy or something, if I could fix it myself I would've sent a pull request!

But now, when I want to upload a .jpg or .png via the media upload screen in an article, I get this error.
![Capture2](https://user-images.githubusercontent.com/2716208/80204346-fecec900-8628-11ea-9f67-456e80554eee.PNG)

Thanks for your quick response on the previous issue btw!

**Comment by nikosdion** [comment]
I confirm the issue and there's been another report so it's definitely a legit bug. I will be looking into this later today.

**Comment by nikosdion** [comment]
Thank you for your report! The issue is now fixed in [release 1.0.2](https://github.com/nikosdion/joomlasvg/releases/tag/1.0.2).
