### ISSUE TITLE
setting non svg file to svg

### ISSUE THREAD

**Issue by Ruud68** [nikosdion/joomlasvg#4]
https://github.com/nikosdion/joomlasvg/blob/aa2806b9882d3832aea0faefef97f2718e8d2fb3/plugins/system/joomlasvg/src/Extension/JoomlaSVG.php#L41-L44

the logic here sets the file to svg when the file extension is not .svg

This leads to issues when using the Joomla Image class for e.g. a .png file
This will then throw an error when trying to manipulate that file:

"Attempting to load an image of unsupported type image/svg+xml"

when changing the !== to == then it works okay, but as I cannot test your plugin I do not know if it still works :)

**Comment by nikosdion** [comment]
The correct solution is to leave the `if` condition as-is and change the subsequent `return` to `false`.
